package co.udea.edu.proyectointegrador.gr11.parqueaderoapp.domain.entities;
// Generated 15/02/2015 12:13:53 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * IngresoId generated by hbm2java
 */
public class IngresoId  implements java.io.Serializable {


     private Date fecha;
     private String placa;
     private String usuarioIdentificacion;

    public IngresoId() {
    }

    public IngresoId(Date fecha, String placa, String usuarioIdentificacion) {
       this.fecha = fecha;
       this.placa = placa;
       this.usuarioIdentificacion = usuarioIdentificacion;
    }
   
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }
    public String getUsuarioIdentificacion() {
        return this.usuarioIdentificacion;
    }
    
    public void setUsuarioIdentificacion(String usuarioIdentificacion) {
        this.usuarioIdentificacion = usuarioIdentificacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IngresoId) ) return false;
		 IngresoId castOther = ( IngresoId ) other; 
         
		 return ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) )
 && ( (this.getPlaca()==castOther.getPlaca()) || ( this.getPlaca()!=null && castOther.getPlaca()!=null && this.getPlaca().equals(castOther.getPlaca()) ) )
 && ( (this.getUsuarioIdentificacion()==castOther.getUsuarioIdentificacion()) || ( this.getUsuarioIdentificacion()!=null && castOther.getUsuarioIdentificacion()!=null && this.getUsuarioIdentificacion().equals(castOther.getUsuarioIdentificacion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         result = 37 * result + ( getPlaca() == null ? 0 : this.getPlaca().hashCode() );
         result = 37 * result + ( getUsuarioIdentificacion() == null ? 0 : this.getUsuarioIdentificacion().hashCode() );
         return result;
   }   


}


