package co.udea.edu.proyectointegrador.gr11.parqueaderoapp.domain.entities;
// Generated 15/02/2015 12:13:53 PM by Hibernate Tools 4.3.1



/**
 * Ingreso generated by hbm2java
 */
public class Ingreso  implements java.io.Serializable {


     private IngresoId id;
     private OperarioUser operarioUser;
     private UsuarioVehiculo usuarioVehiculo;
     private boolean estado;

    public Ingreso() {
    }

    public Ingreso(IngresoId id, OperarioUser operarioUser, UsuarioVehiculo usuarioVehiculo, boolean estado) {
       this.id = id;
       this.operarioUser = operarioUser;
       this.usuarioVehiculo = usuarioVehiculo;
       this.estado = estado;
    }
   
    public IngresoId getId() {
        return this.id;
    }
    
    public void setId(IngresoId id) {
        this.id = id;
    }
    public OperarioUser getOperarioUser() {
        return this.operarioUser;
    }
    
    public void setOperarioUser(OperarioUser operarioUser) {
        this.operarioUser = operarioUser;
    }
    public UsuarioVehiculo getUsuarioVehiculo() {
        return this.usuarioVehiculo;
    }
    
    public void setUsuarioVehiculo(UsuarioVehiculo usuarioVehiculo) {
        this.usuarioVehiculo = usuarioVehiculo;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


