package co.udea.edu.proyectointegrador.gr11.parqueaderoapp.domain.entities;
// Generated 15/02/2015 12:13:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoUsuario generated by hbm2java
 */
public class TipoUsuario  implements java.io.Serializable {


     private int idTipoUsuario;
     private String tipoUsuarioDescripcion;

    public TipoUsuario() {
    }

	
    public TipoUsuario(int idTipoUsuario, String tipoUsuarioDescripcion) {
        this.idTipoUsuario = idTipoUsuario;
        this.tipoUsuarioDescripcion = tipoUsuarioDescripcion;
    }
 
    public int getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(int idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
    public String getTipoUsuarioDescripcion() {
        return this.tipoUsuarioDescripcion;
    }
    
    public void setTipoUsuarioDescripcion(String tipoUsuarioDescripcion) {
        this.tipoUsuarioDescripcion = tipoUsuarioDescripcion;
    }
   
}


