package co.udea.edu.proyectointegrador.gr11.parqueaderoapp.domain.entities;
// Generated 15/02/2015 12:13:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoOperarioUser generated by hbm2java
 */
public class TipoOperarioUser  implements java.io.Serializable {


     private int idTipoOperarioUser;
     private String descripcion;
    

    public TipoOperarioUser() {
    }

	
    public TipoOperarioUser(int idTipoOperarioUser, String descripcion) {
        this.idTipoOperarioUser = idTipoOperarioUser;
        this.descripcion = descripcion;
    }
 
    public int getIdTipoOperarioUser() {
        return this.idTipoOperarioUser;
    }
    
    public void setIdTipoOperarioUser(int idTipoOperarioUser) {
        this.idTipoOperarioUser = idTipoOperarioUser;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
  
}


